---------------CREATING TABLES-----------------

---------------LOCATION TABLE------------------

CREATE TABLE LOCATION_TBL
(
	Loc_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	Street_Address VARCHAR(100) NOT NULL,
	Postal_Code NUMERIC(5) NOT NULL,
	City VARCHAR(25) NOT NULL,
	Province VARCHAR(25) NOT NULL,
	Country VARCHAR(25) DEFAULT 'Pakistan'
)

----------------DEPARTMENT TABLE-----------------

CREATE TABLE DEPARTMENT_TBL
(
	D_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	D_Name VARCHAR(50) NOT NULL,
	Loc_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES LOCATION_TBL(Loc_Id)
)

----------------WARE HOUSE TABLE-------------------

CREATE TABLE WAREHOUSE_TBL
(
	WH_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	WH_Name VARCHAR(50) NOT NULL,
	WH_Size_Sqf NUMERIC(5) NOT NULL,
	Loc_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES LOCATION_TBL(Loc_Id),
	D_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES DEPARTMENT_TBL(D_Id)	
)

----------------RAW MATERIAL TABLE--------------------

CREATE TABLE RAWMATERIAL_TBL
(
	RM_Id NUMERIC(5) NOT NULL PRIMARY KEY,
	RM_Name VARCHAR(50) NOT NULL,
	RM_Quantity NUMERIC(6) NOT NULL,
	RM_Expiry DATE NOT NULL,
	WH_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES WAREHOUSE_TBL(WH_Id)
)

----------------ASSEMBLY LINE TABLE----------------------

CREATE TABLE ASSEMBLYLINE_TBL
(
	AL_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	AL_Name VARCHAR(50) NOT NULL,
	AL_Function VARCHAR(100) NOT NULL,
	AL_Units_Per_Day NUMERIC(4) NOT NULL,
	D_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES DEPARTMENT_TBL(D_Id)
)

----------------------PRODUCT TABLE-------------------------

CREATE TABLE PRODUCT_TBL
(
	P_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	P_Name VARCHAR(50) NOT NULL,
	P_Type VARCHAR(50) NOT NULL,
	P_Price NUMERIC(10) NOT NULL,
	P_Quantity NUMERIC(5) NOT NULL,
	P_Expiry DATE NOT NULL,
	WH_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES WAREHOUSE_TBL(WH_Id),
	AL_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES ASSEMBLYLINE_TBL(AL_Id)
)

-------------------ASSEMBLY USE RAW TABLE-----------------------

CREATE TABLE PRODUCT_USE_RAW_TBL
(
	P_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES PRODUCT_TBL(P_Id),
	RM_Id NUMERIC(5) NOT NULL FOREIGN KEY REFERENCES RAWMATERIAL_TBL(RM_Id),
	Raw_Used NUMERIC(4) NOT NULL,
	CONSTRAINT PK_PRM_ID PRIMARY KEY (P_Id , RM_Id)
)

--------------------ADMINITRATION TABLE------------------------

CREATE TABLE ADMINISTRATION_TBL
(
	ADM_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	ADM_First_Name VARCHAR(50) NOT NULL,
	ADM_Last_Name VARCHAR(50) NOT NULL,
	ADM_Position VARCHAR(50) NOT NULL,
	ADM_Salary NUMERIC(8),
	ADM_Phone NUMERIC(15) NOT NULL,
	ADM_SSN NUMERIC(15) UNIQUE,
	ADM_Manager NUMERIC(4) FOREIGN KEY REFERENCES ADMINISTRATION_TBL(ADM_Id),
	D_Id NUMERIC(4) FOREIGN KEY REFERENCES DEPARTMENT_TBL(D_Id)
)

---------------------ADMIN DETAIL TABLE-----------------------------

CREATE TABLE ADMINDETAIL_TBL
(
	ADM_CNIC NUMERIC(15) NOT NULL UNIQUE,
	ADM_Email VARCHAR(50) UNIQUE,
	ADM_Gender VARCHAR(10) NOT NULL,
	ADM_Address VARCHAR(50) NOT NULL,
	ADM_DOB DATE NOT NULL,
	ADM_BloodGroup VARCHAR(10),
	ADM_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES ADMINISTRATION_TBL(ADM_Id)
)

--------------------WORKER TABLE------------------------

CREATE TABLE WORKER_TBL
(
	W_Id NUMERIC(4) NOT NULL PRIMARY KEY,
	W_First_Name VARCHAR(50) NOT NULL,
	W_Last_Name VARCHAR(50) NOT NULL,
	W_Position VARCHAR(50) NOT NULL,
	W_Salary NUMERIC(8),
	W_Phone NUMERIC(15) NOT NULL,
	W_SSN NUMERIC(15) UNIQUE,
	W_Supervisor NUMERIC(4) FOREIGN KEY REFERENCES WORKER_TBL(W_Id),
	AL_Id NUMERIC(4) FOREIGN KEY REFERENCES ASSEMBLYLINE_TBL(AL_Id),
	WH_Id NUMERIC(4) FOREIGN KEY REFERENCES WAREHOUSE_TBL(WH_Id),
	D_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES DEPARTMENT_TBL(D_Id),
	ADM_Id NUMERIC(4) FOREIGN KEY REFERENCES ADMINISTRATION_TBL(ADM_Id)
)

---------------------ADMIN DETAIL TABLE-----------------------------

CREATE TABLE WORKERDETAIL_TBL
(
	W_CNIC NUMERIC(15) NOT NULL UNIQUE,
	W_Email VARCHAR(50) UNIQUE,
	W_Gender VARCHAR(10) NOT NULL,
	W_Address VARCHAR(50) NOT NULL,
	W_DOB DATE NOT NULL,
	W_BloodGroup VARCHAR(10),
	W_Id NUMERIC(4) NOT NULL FOREIGN KEY REFERENCES WORKER_TBL(W_Id)
)

------------------------------------------------------------------------------------------------------------------